#!/bin/lua

--[[
 * Copyright (C) 2016 Red Hat, Inc.
 * Author: Bastien Nocera <hadess@hadess.net>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA.
 *
--]]

local fg = require "lib.flatpak-game"

function usage()
	print("game-to-flatpak [--network] [--repo=DIR] [--keep-build-dir] [--bundle] [--keep-repo-dir] [FILE...]")
end

local file = nil
local options = {}

for k, v in ipairs(arg) do
	if string.sub (v, 1, 2) == "--" then
		if v == '--network' then
			options.network = true
		elseif string.sub(v, 1, 7) == '--repo=' then
			options.repo_dir = string.gsub(v, '--repo=', '')
		elseif v == '--keep-build-dir' then
			options.keep_build_dir = true
		elseif v == '--keep-repo' then
			options.keep_repo_dir = true
		elseif v == '--bundle' then
			options.bundle = true
		else
			print ("Unknown option '" .. v .. "'")
			usage()
			return 1
		end
	else
		file = v
		break
	end
end

if not options.repo_dir then
	options.repo_dir = 'repo'
elseif not options.keep_repo_dir then
	-- Adding it to your local repo and also making a bundle should not delete
	-- the whole local repo.
	print('Repo directory defined, assuming --keep-repo.')
	options.keep_repo_dir = true
end

if not file then
	usage()
	return 1
end

local ret = handle(file, options)
return ret
